### ISSUE TITLE
Webpacker Support

### ISSUE THREAD

**Issue by inicklas** [dkniffin/active_material#74]
Hi,
Thanks for providing us with this beaut. Just wondering if there is an npm / support for webpack at the moment. thank you.

**Comment by dkniffin** [comment]
Yes, please support webpacker. [Activeadmin now supports webpacker](https://github.com/activeadmin/activeadmin/issues/5558), but I can't migrate easily until this is done.

**Comment by fabn** [comment]
+1 for this

**Comment by fabn** [comment]
This may be relevant: https://github.com/cprodhomme/arctic_admin/issues/72

**Comment by dkniffin** [comment]
An update here: I got this repo transferred over to me and I'll be maintaining it now. I'll look into taking care of this soon, as well as reviewing the other open issues and PRs.

**Comment by dkniffin** [comment]
Another side-note: I learned that the official gem on rubygems was created by someone that wasn't the owner of this repo. I'm working on getting that transferred over to me as well.

**Comment by blackjid** [comment]
> Another side-note: I learned that the official gem on rubygems was created by someone that wasn't the owner of this repo. I'm working on getting that transferred over to me as well.

sorry about that :(

**Comment by dkniffin** [comment]
@blackjid No worries! Thank you for transferring ownership over to me so that I can get it all back inline.

**Comment by andre-filho** [comment]
Hi, is webpacker support still a WIP?

**Comment by dkniffin** [comment]
@andre-filho Yes, unfortunately I have not had time to add this support yet. I was hoping the site I work on for my day job would need this soon and I'd be able to tackle it as part of that, but that work got back-burnered and I haven't found any free time yet. I have not forgotten about this though. It's on my todo list, just lower down than some other things.

**Comment by dkniffin** [comment]
I have just finished adding npm package support (and thus webpacker support). Unfortunately, in order to do so, I had to convert the way fonts are being imported (see #81 for details on that). Therefore, I was unable to continue supporting Sprockets.

I also realized that there's not any actual ruby code for this library. So I've removed the ruby gem code and converted this entirely to an npm/JS package.

Those are both very large breaking changes, so I've bumped the version to v2 in the process (see #82 for details on that).
